version: "2"

services:
  zookeeper:
    image: zookeeper:3.4
    container_name: zookeeper
    networks:
      - hbase
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888

networks:
  hbase:
    external: true
